### ISSUE TITLE
Add tenant support

### ISSUE THREAD

**Issue by jakobrosenberg** [FusionAuth/fusionauth-node-client#1]
Any chance of getting tenant support for this library?

**Comment by robotdan** [comment]
Hi @jakobrosenberg , thanks for the request. Do you mean just the support for the `X-FusionAuth-TenantId` header as there is in the Java Client?  

https://github.com/FusionAuth/fusionauth-java-client/blob/master/src/main/java/io/fusionauth/client/FusionAuthClient.java

Yes, I can get that out for you. In the mean time, you could also use tenant scoped API keys.
https://fusionauth.io/docs/v1/tech/tutorials/tenants#make-an-api-call-for-a-specific-tenant

**Comment by robotdan** [comment]
I stubbed out the change, it should work in theory.  I did some sanity testing, but I'll leave this open until I complete testing. 

To use this with a Tenant, call it like this, where `api-key` is your API key and `65323339-6137-6531-3135-316238623265` is the Tenant Id.

```
const client = new FusionAuthClient('api-key', 'http://localhost:9021')
                                   .setTenantId('65323339-6137-6531-3135-316238623265');
```

**Comment by jakobrosenberg** [comment]
Sorry, I should have been more clear. I meant CRUD functionality for tenants. At the moment I'm using the rest API to create and delete tenants.

**Comment by robotdan** [comment]
Ah. Got it. 

That should already be available. See `createTenant`, `deleteTenant`. Is there a method that is missing?

**Comment by jakobrosenberg** [comment]
Sorry again. You had it right all along.

I had worked around the issue with ``axios`` and forgot what the issue was. Is there an advantage in using your native library compared to axios?

**Comment by robotdan** [comment]
Thanks for the update @jakobrosenberg - no worries. Happy to help. 

> Is there an advantage in using your native library compared to axios?

I've never used [axios](https://github.com/axios/axios), but it looks like a good option. Feel free to use what works best for you. The main benefit if of using our client library is the named methods w/ jsdoc. 

But if  you just want to work off the API docs with axios, that sounds good to me. 

Let us know if we can be of further assistance.
