### ISSUE TITLE
Can't access refresh token

### ISSUE THREAD

**Issue by Tahakun** [FusionAuth/fusionauth-node-client#10]
I can't access the refresh as it's sent in the headers, tried both the login() and retrieveRefreshTokens() methods, as the refresh token is always sent in the header.

I think for functions involving the refresh token, the API client should append the refresh token to the response body

**Comment by robotdan** [comment]
Both of these APIs return a response body containing the token. 

https://fusionauth.io/docs/v1/tech/apis/jwt#retrieve-refresh-tokens
https://fusionauth.io/docs/v1/tech/apis/login#authenticate-a-user

Can you confirm using a basic REST client such as `cURL` , Postman or Insomnia?

**Comment by Tahakun** [comment]
Found the solution, it looks like the "Generate refresh tokens" option wasn't enabled in the application config.
Thank you.
