### ISSUE TITLE
Method to change password using JWT

### ISSUE THREAD

**Issue by jose-magalhaes-deel** [FusionAuth/fusionauth-node-client#2]
Hi! Do we have the possibility to change password using JWT in the 1.5 version?
Thank you.

**Comment by robotdan** [comment]
Hi @JEduardogmr Were you able to answer your question, or did you need any assistance? 

For future reference, the main issues project will be a better spot to ask this question. 
https://github.com/FusionAuth/fusionauth-issues/issues

1.5.0 does allow you to change the User's password using a JWT. The documentation will be updated shortly to reflect this scenario. 

The high level work flow will be as follows:

1. Call the [`/api/user/change-password`](https://fusionauth.io/docs/v1/tech/apis/users#change-a-users-password) API with [JWT authentication](https://fusionauth.io/docs/v1/tech/apis/authentication)
2. This request will require the current password as well as the new one. 
3. This API response will contain a `oneTimePassword` that can be optionally used to call the Login API.

This last step is for usability. For example, if you're in an SPA, or other workflow and the you're using Refresh Tokens, changing a user's password will revoke their current refresh token. This `oneTimePassword` will allow you to programmatically log the user back in to acquire new tokens so the user does not have to log back in with the new credentials they just gave you during the change password request.

**Comment by jose-magalhaes-deel** [comment]
Hi @robotdan. I was looking on the node client for a method to change password using JWT, but i came to the conclusion that i don't need it. That new endpoint it's probably more useful for a direct call from, for example, an SPA, wich is not my case.

Anyway, thank for your reply!

**Comment by robotdan** [comment]
Ah, ok got. Hmm.., good point though. Some users may wish to use the clients to perform this task, maybe through the typescript or native Javascript clients. 

I'll add an issue to get this added just in case anyone wants it. We do have at least one other client method that takes a JWT so there is some precedence. (i.e. `retrieveUserUsingJWT`)

Thanks for using FusionAuth!
