### ISSUE TITLE
FusionAuthClient.login method not returning JWT cookie headers

### ISSUE THREAD

**Issue by UniRoomy** [FusionAuth/fusionauth-node-client#4]
Posting directly to /api/login with the same JSON body responds with the correct Set-Cookie header for a JWT access token.

Through this API (FusionAuthClient.login(jsonObj)) the exact same body is returned, but no Set-Cookie header. Same server, same application, same authentication etc etc.

**Comment by robotdan** [comment]
Hi @UniRoomy, when using the node client, we'll only return the JSON body from the `login` method.

We return the JWT in both a `Set-Cookie` header and in the JSON response body.  See the `token` field in the response body section. In your case, you can utilize the `token` response field. 

https://fusionauth.io/docs/v1/tech/apis/login#authenticate-a-user

Let me know if you need further assistance.

**Comment by UniRoomy** [comment]
Thanks @robotdan - I thought that may be the case!
